import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import { Box } from '@mui/material';
import { AppTitle, AppButtonLink } from '../src/components/';

export default function Home() {
	const router = useRouter();
	
	return (
		<div>
		  	<Head>
				<title>Fake Astro</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<Box sx={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-around', alignItems: 'center', height: '100vh', backgroundSize: 'cover', backgroundRepeat: 'no-repeat', backgroundImage: 'url(background.webp)'}}>
					<Box>
						<AppTitle>
							Take psychological <AppButtonLink value="quizzes" href="/quiz/egoNeed"/>.
						</AppTitle>
						<AppTitle>
							Keep a <AppButtonLink value="journal" />.
						</AppTitle>
						<AppTitle>
							All our <AppButtonLink value="articles" />.
						</AppTitle>
					</Box>
					<Box sx={{height: 235, width: 200,  backgroundSize: 'cover', backgroundRepeat: 'no-repeat', backgroundImage: 'url(logo_resolucao.png)'}}></Box>
				</Box>
			</main>
    	</div>
  )
}
