import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import { AppNavBar } from '../src/components';
import { HomeScreen } from '../src/screens';

export default function Home() {
	const router = useRouter();
   	const [sessionId, setSessionId] = useState(router.query.hash ?? "");
   	const isUserLogged = () => (sessionId ? true : false);
	const [screen, setScreen] = useState(0);

	const screens = [<HomeScreen/>];
	
	return (
		<div>
		  	<Head>
				<title>Fake Astro</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
				<meta name="viewport" content="initial-scale=1, width=device-width" />
			</Head>
			<main>
				<AppNavBar userLogged={isUserLogged()} logoutFunction={(e) => setSessionId("")} />
				{screens[screen]}
			</main>
    	</div>
  )
}
