import Head from 'next/head'
import Button from '@mui/material/Button';
import { AppNavBar } from '../src/components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fake Astro</title>
        <meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
				<meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>

      <main>
		<AppNavBar />
      </main>
    </div>
  )
}
